### ISSUE TITLE
(Minor) Allow `options.paths` to be an array or single object

### ISSUE THREAD

**Issue by gardinbe** [tinchoz49/esbuild-plugin-copy-watch#3]
Best esbuild copy plugin out of the many i've tried 👍 

Very minor request, but to allow the api to function like this might be nice:

```typescript
copy({
  paths: { from: 'public', to: 'assets' }
})
```

Using a single object instead of an array of from-to objects.

**Comment by tinchoz49** [comment]
Hey @gardinbe , thanks for your feedback, in this case I prefer to maintain one single option type to use.
