### ISSUE TITLE
Not triggering after rebuild

### ISSUE THREAD

**Issue by gardinbe** [tinchoz49/esbuild-plugin-copy-watch#4]
https://github.com/tinchoz49/esbuild-plugin-copy-watch/blob/7e5e9a14d2cabdf6ff79149b40308da2efc1ad49/src/index.js#L161-L174

Within with chokidar watch options object, there is the property `ignoreIntitial` which defaults to `false`.

The description of this property is as follows:

> If set to false then add/addDir events are also emitted for matching paths while instantiating the watching as chokidar discovers these > file paths (before the ready event).

In other words, the 'add' event will be fired for every file detected when the watcher is first initialized, correctly copying all the files to the dest dir. This means that all files are correctly copied on an initial build.

However, on a rebuild within esbuild watch mode, the chokider watcher is not re-initialized, and so it will not copy these files over again. This would normally be fine, however, I'm using [esbuild-plugin-clean](https://github.com/LinbuduLab/esbuild-plugins/tree/main/packages/esbuild-plugin-clean), which empties the target directory on every rebuild.

As a result, rebuilds for me cause the copied files to be deleted and not re-added.

I think it should be expected that any rebuild should cause the files to be copied across again, even if they havent been modified.

An easy fix would be to recreate the chokidar watcher instance every time the `build.onEnd` function is fired.

I think a proper fix might be to enable `ignoreInitial` and then manually copy the entire directory across every time `build.onEnd` is fired.

**Comment by tinchoz49** [comment]
The v2.3.0 version should help you with the flag `forceCopyOnRebuild`

**Comment by gardinbe** [comment]
seems to be working like a charm 👍
