### ISSUE TITLE
Node processes not being released

### ISSUE THREAD

**Issue by gardinbe** [tinchoz49/esbuild-plugin-copy-watch#5]
![image](https://github.com/tinchoz49/esbuild-plugin-copy-watch/assets/55744452/bb40815f-ba52-43f7-b21c-d36d8a2beebc)

For some reason, even after hitting CTRL-C to stop the esbuild watcher process, I have two node processes that aren't being released.

Obviously its probably not great to have unreleased processes in the background. But also, this is also a bit problematic in that sometimes these un-released processes hold their locks on some files, which can show up as errors in subsequent runs of esbuild:

![image](https://github.com/tinchoz49/esbuild-plugin-copy-watch/assets/55744452/9cddb942-3d5c-458c-93b9-e06d908de507)

I have isolated this issue to be with this package, as I've tested with/without this plugin and the issue is only present when I've got it added.

Honestly have no idea whats causing this... maybe there's a timeout that's not been cleared? Or maybe `onDispose` isn't called in the same way if a user presses CTRL-C?

**Comment by gardinbe** [comment]
Yeah, ive just done a quick test now, seems like `onDispose` isn't called when CTRL-C is pressed. Maybe there could be another way to check if the build has cancelled? Perhaps like this:

```javascript
process.on('SIGINT', function () {
  console.log('Caught interrupt signal');
  // run the same code as below ↓↓↓↓
});
```

https://github.com/tinchoz49/esbuild-plugin-copy-watch/blob/25fcdda733e83c95dc5c3d0ca91f046419635797/src/index.js#L184-L189

Hooking into the node sigint event to see if the process has been stopped?

Not sure if that'll fix it, just an idea.

**Edit**: Ive tested it and it works, no more lingering processes. Not sure if its the best solution though.

**Comment by tinchoz49** [comment]
try the v2.3.1

**Comment by gardinbe** [comment]
Yep, that's done it 👍 Thanks for the fast responses, really helpful! 😄
